//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public PAGO()
        {
            this.Detalle_Pago = new HashSet<Detalle_Pago>();
        }
    
        public int IdPago { get; set; }
        public string TipoPago { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual ICollection<Detalle_Pago> Detalle_Pago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
